language: python
os:
  - linux
  - windows
python:
  - 3.7
cache: pip
install:
  - pip install requests
  - pip install python-dateutil
  - pip install selenium
  - chmod +x setup.py
script: ./setup.py
